### ISSUE TITLE
[Landing Page] Heading overflow in Hero section

### ISSUE THREAD

**Issue by hreyesm** [andresmgsl/solana-cohort-june-2022#24]
At certain viewport widths, the heading in the Hero section will exceed the width of its parent container:
<img width="764" alt="Screen Shot 2022-06-22 at 16 55 01" src="https://user-images.githubusercontent.com/36577958/175149893-290afefe-bd20-4a46-9a85-02762e1ab0f3.png">
<img width="1093" alt="Screen Shot 2022-06-22 at 16 54 54" src="https://user-images.githubusercontent.com/36577958/175150189-a7d870c5-e5a8-43b1-bdfa-8a4612274a92.png">

**Comment by ZeyadTarekk** [comment]
#26 fixes this
